#version: "3.9"
#
#services:
#  mysql-db:
#    image: mysql:8
#    container_name: mysql-db
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: admin
#      MYSQL_DATABASE: ecommerce
#    ports:
#      - "3307:3306"
#    networks:
#      - app-network
#
#  java-app:
#    image: java-application
#    container_name: java-app
#    restart: always
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mysql-db
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/ecommerce
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: admin
#    networks:
#      - app-network
#
#networks:
#  app-network:
#    driver: bridge
